# In this notebook , we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically we're going to cover :

    * Introduction to tensors
    * Getting information form tensors
    * Manipulating Tensors
    * Tensors & Numpy
    * Using @tf.function (a way to speed up your regular Python functions)
    * Using GPU with TensorFlow (or TPUs)
    * Exercises to try for yourself!

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the number of dimensions in the matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specifying the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions in another_matrix ?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far :

* Scalar : a single number
* Vector : a number with direction (e.g. wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with tf.variable

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change one of the elements in our changeable tensor
# changeable_tensor[0] = 7
# changeable_tensor

# This will give error , so it is not executed . Proper method is displayed below

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor
# unchangeable_tensor[0].assign(7)
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

🔑 Note : Rarely in practice you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(69) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(69)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.29164317,  1.4531525 ],
        [-0.8223833 , -1.3446563 ],
        [-0.7183838 , -0.20373915]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.29164317,  1.4531525 ],
        [-0.8223833 , -1.3446563 ],
        [-0.7183838 , -0.20373915]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle the data so the inherent pattern of data doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
# If we only put one random seed in the shuffle command, it doesn't give shuffled tensors in the same order (not reproducible results) ,
# so we also put global random seed alongwith operation level random seed
tf.random.set_seed(69)  # global level random seed
tf.random.shuffle(not_shuffled, seed=69)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU.

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors we need to be aware of the following attributes :
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Checking the 0th element in the rank 4 matix
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0]) # This refers to the number of elements in the first position i.e. in 2's position of [2,3,4,5]
print("Elements along the last axis: ", rank_4_tensor.shape[-1]) # This refers to the number of elements in the last position i.e. in 5's position of [2,3,4,5]
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy()) # by adding this we get the no. of elements in the tensor , in a single element

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing Tensros

Tensors can be indexed just like python lists.


In [ ]:
# Get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank two tensor (2 dimensions)
rank_2_tensor = tf.constant([[1,2],
                            [3,4]])
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Get the last item of each row from our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
# This adds a new axis to our trensor thereby allowing to reshape it without changing the contents of the tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Here the ... means include every axis before the last one
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Here we are expanding from the first axis instead of the last axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor opeartions)

**Basic operations**

`+`,`-`,`*`,`/`

In [ ]:
# You can add values in a tensor using the addition opeartor
tensor = tf.constant([[1,5],
                      [2,6]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 15],
       [12, 16]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 60],
       [24, 72]], dtype=int32)>

In [ ]:
# Same for subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -5],
       [-8, -4]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in functions too
tf.multiply(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 25],
       [10, 30]], dtype=int32)>

In [ ]:
tf.divide(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 1. ],
       [0.4, 1.2]])>

**Matrix Multiplication**

In Machine learning , matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) must follow to fulfil if we're going to matrix multiply them :    
1. The inner dimensions must match.
2. The resulting matrix has the shape of the inner dimensions.

In [ ]:
# Matrix multiplication in Tensorflow
print(tensor)
tf.matmul(tensor,tensor) # This matmul func. is used to multiply two tensors in tf

tf.Tensor(
[[1 5]
 [2 6]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 35],
       [14, 46]], dtype=int32)>

In [ ]:
# Matrix multiplication with python opearator
tensor @ tensor # This is the same as tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 35],
       [14, 46]], dtype=int32)>

In [ ]:
# Create a tensor of (3,2) shape
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another (3,2) tensor
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

### Now if we try to multiply these two matrices , we will get an error as the shape is not compatible in accordance to matrix multiplication rules

In [ ]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# We could also reshape the matrix (tensor) for this matrix multiplication
tf.reshape(X,shape =(2,3))
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

### Note that , reshaping a matrix and multiplying with another matrix gives different dot product as compared to finding out transpose of the same matrix and multiplying with another matrix .

**The Dot Product**

Matrix multiplication is also referred to as dot product.
We can perform matrix multiplication using :       
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
# Performing the dot product on X and Y using tensordot
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up , you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregating Tensors

Aggregating tensors means condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Getting the absolute values
A = tf.constant([-12,-19,-10])
tf.abs(A)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 19, 10], dtype=int32)>

Let's go through the following forms of aggregation :
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Creating a random tensor
P = tf.constant([20, 12, 15, 23, 10])
Q = tf.constant([[5,10],
                 [15,20]])
P , Q , P.dtype, Q.dtype

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([20, 12, 15, 23, 10], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 10],
        [15, 20]], dtype=int32)>,
 tf.int32,
 tf.int32)

In [ ]:
# To find the minimum value in a tensor
tf.reduce_min(P) , tf.reduce_min(Q)

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>)

In [ ]:
# To find the maximum value in a tensor
tf.reduce_max(P) , tf.reduce_max(Q)

(<tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(), dtype=int32, numpy=20>)

In [ ]:
# To find the mean of a tensor
tf.reduce_mean(P) , tf.reduce_mean(Q)

(<tf.Tensor: shape=(), dtype=int32, numpy=16>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [ ]:
# To find the sum of values in a tensor
tf.reduce_sum(P) , tf.reduce_sum(Q)

(<tf.Tensor: shape=(), dtype=int32, numpy=80>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [ ]:
# This R and S tensors are just created to include some float values , the var and std could be done on normal integer data too
R = tf.constant(np.arange(0,1,0.1))
S = tf.constant(np.arange(1,2,0.1))
R , R.dtype, R.ndim , R.shape , S , S.dtype, S.ndim , S.shape

(<tf.Tensor: shape=(10,), dtype=float64, numpy=array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])>,
 tf.float64,
 1,
 TensorShape([10]),
 <tf.Tensor: shape=(10,), dtype=float64, numpy=array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])>,
 tf.float64,
 1,
 TensorShape([10]))

In [ ]:
# Earlier we were using math.reduce functions but var and std require a different tf probs library (can also be done without importing this library) so we import that
# The alternate step for doing this without importing a different library is shown later below
import tensorflow_probability as tfp

In [ ]:
# To find the variance of a tensor in tensorflow
tfp.stats.variance(P) , tfp.stats.variance(Q) , tfp.stats.variance(R) , tfp.stats.variance(S)

(<tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 25], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.0825>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.08250000000000016>)

In [ ]:
# To find the standard deviation of values in a tensor
# Note that here we are using only the tensors which ahve float values
# We cannot use the tensors which have int data type directly , as it is not supported
tfp.stats.stddev(R) , tfp.stats.stddev(S)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.2872281323269014>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.2872281323269017>)

In [ ]:
# Here we are finding the std of a tensor with originally int type values by casting them into float type values
tfp.stats.stddev(tf.cast(P, dtype = tf.float32)) , tfp.stats.stddev(tf.cast(Q, dtype = tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=4.857983>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 5.], dtype=float32)>)

Finding mean and standard deviation without using tensorflow probability

In [ ]:
# Find the variance of our E tensor using reduce.math
tf.math.reduce_variance(tf.cast(P, dtype = tf.float32)) , tf.math.reduce_variance(tf.cast(Q, dtype = tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=23.6>,
 <tf.Tensor: shape=(), dtype=float32, numpy=31.25>)

In [ ]:
# Find the std of our E tensor using reduce.math
tf.math.reduce_std(tf.cast(P, dtype = tf.float32)) , tf.math.reduce_std(tf.cast(Q, dtype = tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=4.857983>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.59017>)

### Finding the positional maximum and minimum of a tensor

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(69)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([5.3272355e-01, 7.6764774e-01, 7.6187789e-01, 2.5841391e-01,
       5.6738329e-01, 1.3471830e-01, 4.7002292e-01, 3.5524964e-02,
       3.8393617e-01, 1.6981947e-01, 4.4886672e-01, 5.6220615e-01,
       5.1936674e-01, 7.7804303e-01, 3.4848118e-01, 5.6664705e-01,
       6.1973441e-01, 3.1386054e-01, 5.0863159e-01, 1.2493873e-01,
       6.2286139e-01, 3.9865887e-01, 8.9437950e-01, 8.0250156e-01,
       6.0539913e-01, 6.2322211e-01, 6.9168448e-01, 3.2230341e-01,
       5.5286503e-01, 6.8580091e-01, 9.3656206e-01, 7.2395742e-01,
       9.7975111e-01, 6.0671389e-01, 9.5694554e-01, 8.5030973e-01,
       2.1026397e-01, 6.1866856e-01, 7.4614286e-01, 9.3863714e-01,
       7.7380419e-01, 9.8344505e-01, 8.8855958e-01, 5.8377409e-01,
       2.5783134e-01, 4.4455886e-02, 1.0716915e-04, 4.2767525e-03,
       4.6135592e-01, 3.7454653e-01], dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98344505>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.98344505>

We can see that our element in largest value position matches our maximum valued element in the tensor so it is justified

Similarly we can find the positional minimum using argmin , and check whether the element in that psotion matches the lowest element in the tensor

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(69)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[5.3272355e-01, 7.6764774e-01, 7.6187789e-01, 2.5841391e-01,
           5.6738329e-01, 1.3471830e-01, 4.7002292e-01, 3.5524964e-02,
           3.8393617e-01, 1.6981947e-01, 4.4886672e-01, 5.6220615e-01,
           5.1936674e-01, 7.7804303e-01, 3.4848118e-01, 5.6664705e-01,
           6.1973441e-01, 3.1386054e-01, 5.0863159e-01, 1.2493873e-01,
           6.2286139e-01, 3.9865887e-01, 8.9437950e-01, 8.0250156e-01,
           6.0539913e-01, 6.2322211e-01, 6.9168448e-01, 3.2230341e-01,
           5.5286503e-01, 6.8580091e-01, 9.3656206e-01, 7.2395742e-01,
           9.7975111e-01, 6.0671389e-01, 9.5694554e-01, 8.5030973e-01,
           2.1026397e-01, 6.1866856e-01, 7.4614286e-01, 9.3863714e-01,
           7.7380419e-01, 9.8344505e-01, 8.8855958e-01, 5.8377409e-01,
           2.5783134e-01, 4.4455886e-02, 1.0716915e-04, 4.2767525e-03,
           4.6135592e-01, 3.7454653e-01]]]]], dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([5.3272355e-01, 7.6764774e-01, 7.6187789e-01, 2.5841391e-01,
        5.6738329e-01, 1.3471830e-01, 4.7002292e-01, 3.5524964e-02,
        3.8393617e-01, 1.6981947e-01, 4.4886672e-01, 5.6220615e-01,
        5.1936674e-01, 7.7804303e-01, 3.4848118e-01, 5.6664705e-01,
        6.1973441e-01, 3.1386054e-01, 5.0863159e-01, 1.2493873e-01,
        6.2286139e-01, 3.9865887e-01, 8.9437950e-01, 8.0250156e-01,
        6.0539913e-01, 6.2322211e-01, 6.9168448e-01, 3.2230341e-01,
        5.5286503e-01, 6.8580091e-01, 9.3656206e-01, 7.2395742e-01,
        9.7975111e-01, 6.0671389e-01, 9.5694554e-01, 8.5030973e-01,
        2.1026397e-01, 6.1866856e-01, 7.4614286e-01, 9.3863714e-01,
        7.7380419e-01, 9.8344505e-01, 8.8855958e-01, 5.8377409e-01,
        2.5783134e-01, 4.4455886e-02, 1.0716915e-04, 4.2767525e-03,
        4.6135592e-01, 3.7454653e-01], dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green , blue , purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specifying custom values for one hot encoding
tf.one_hot(some_list,depth = 4, on_value = "I'm diggin it", off_value = "I'm not diggin it")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"I'm diggin it", b"I'm not diggin it", b"I'm not diggin it",
        b"I'm not diggin it"],
       [b"I'm not diggin it", b"I'm diggin it", b"I'm not diggin it",
        b"I'm not diggin it"],
       [b"I'm not diggin it", b"I'm not diggin it", b"I'm diggin it",
        b"I'm not diggin it"],
       [b"I'm not diggin it", b"I'm not diggin it", b"I'm not diggin it",
        b"I'm diggin it"]], dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the sqaure root (method requires non-int type, thus we make it float)
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow interacts beautifully with NumPy array.

🔑**Note**: One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a TPU or GPU (for faster numerical processing).

In [ ]:
# Create a tensor directly from NumPy array
J = tf.constant(np.array([6,9,69,6969]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([   6,    9,   69, 6969])>

In [ ]:
# Convert our tensor back to a numpy array
np.array(J), type(np.array(J))

(array([   6,    9,   69, 6969]), numpy.ndarray)

In [ ]:
# Convert tensor J into a Numpy array
J.numpy(), type(J.numpy())

(array([   6,    9,   69, 6969]), numpy.ndarray)

In [ ]:
J = tf.constant([3.0])
J.numpy()

array([3.], dtype=float32)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype


(tf.float64, tf.float32)

In [ ]:
### Finding access to GPUs
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

🔑**Note**: If you have access to a CUDA-enabled GPU , TensorFlow will automatically use it whenever possible.

## **TensorFlow Exercises** for Practice

In [ ]:
scalar = tf.constant(69)
vector = tf.constant([1,3,5,7,9])
matrix = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor = tf.constant([1,2,3,4,5])
print(scalar.shape, vector.shape, matrix.shape, tensor.shape)
print(scalar.ndim, vector.ndim, matrix.ndim, tensor.ndim)
print(tf.size(scalar), tf.size(vector), tf.size(matrix), tf.size(tensor))

() (5,) (2, 2, 3) (5,)
0 1 3 1
tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(5, shape=(), dtype=int32) tf.Tensor(12, shape=(), dtype=int32) tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
rando_tensor = tf.random.uniform(shape = [5,300], maxval = 1)
rando_tensor_2 = tf.random.uniform(shape = [5,300], maxval = 1)
print(rando_tensor)
print(rando_tensor_2)
tf.matmul(rando_tensor, tf.transpose(rando_tensor_2)) , rando_tensor*rando_tensor_2

tf.Tensor(
[[0.66971385 0.42558372 0.9293258  ... 0.94548476 0.59057057 0.297678  ]
 [0.57994354 0.7944716  0.08377779 ... 0.22587013 0.31224263 0.0871948 ]
 [0.4165398  0.792717   0.1444757  ... 0.5325849  0.1004411  0.450073  ]
 [0.5230192  0.5122311  0.9533144  ... 0.33249736 0.03613663 0.31080854]
 [0.00616026 0.91481316 0.58900213 ... 0.17114961 0.75827384 0.33577096]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.6216024  0.21715796 0.82227314 ... 0.4070983  0.6445987  0.83410656]
 [0.54126227 0.5809537  0.54659    ... 0.9756745  0.15846753 0.08773339]
 [0.20031321 0.7614219  0.39034605 ... 0.43138278 0.9360678  0.6819711 ]
 [0.5777608  0.04499626 0.04300141 ... 0.260615   0.9956461  0.2125622 ]
 [0.5419458  0.47968936 0.12248731 ... 0.3929026  0.24408484 0.61974657]], shape=(5, 300), dtype=float32)


(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[83.138756, 74.70706 , 74.674225, 79.33263 , 77.250435],
        [80.748535, 73.676575, 70.96691 , 80.372314, 76.73826 ],
        [74.102196, 69.296936, 70.486946, 75.55278 , 76.19861 ],
        [86.406204, 79.307594, 75.44869 , 84.51643 , 82.56376 ],
        [75.76041 , 68.23783 , 64.88422 , 75.976974, 70.76161 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.41629574, 0.09241889, 0.7641597 , ..., 0.38490522, 0.38068104,
         0.24829517],
        [0.31390154, 0.46155125, 0.0457921 , ..., 0.22037573, 0.04948032,
         0.0076499 ],
        [0.08343842, 0.6035921 , 0.05639552, ..., 0.22974795, 0.09401968,
         0.30693677],
        [0.30218   , 0.02304848, 0.04099387, ..., 0.0866538 , 0.03597929,
         0.06606615],
        [0.00333853, 0.43882614, 0.07214528, ..., 0.06724513, 0.18508315,
         0.2080929 ]], dtype=float32)>)

In [ ]:
rando_tensor_3 = tf.random.Generator.from_seed(69)
rando_tensor_3 = tf.random.uniform(shape=[224,224,3], maxval = 1)
tf.reduce_min(rando_tensor_3, axis=0), tf.reduce_max(rando_tensor_3, axis=0)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[3.62980366e-03, 8.52811337e-03, 6.43491745e-04],
        [6.39557838e-04, 3.54254246e-03, 4.42802906e-03],
        [2.51519680e-03, 2.17148066e-02, 2.87044048e-03],
        [3.98027897e-03, 4.39774990e-03, 1.44398212e-03],
        [1.87325478e-03, 8.68272781e-03, 4.85265255e-03],
        [8.16702843e-04, 5.82575798e-03, 5.26309013e-04],
        [4.99010086e-04, 1.44730806e-02, 7.61532784e-03],
        [1.17063522e-04, 1.48880482e-03, 7.40635395e-03],
        [1.75392628e-03, 5.45918941e-03, 2.25520134e-03],
        [4.64916229e-04, 7.43401051e-03, 1.58953667e-03],
        [3.92556190e-03, 3.60560417e-03, 9.38987732e-03],
        [1.40570402e-02, 2.88844109e-04, 2.77233124e-03],
        [1.67608261e-03, 5.40840626e-03, 6.56390190e-03],
        [4.51326370e-04, 2.35080719e-03, 8.74686241e-03],
        [4.71472740e-03, 1.71124935e-03, 8.64684582e-03],
        [7.04061985e-03, 5.46956062e-03, 8.66091251e-03],
        [3.88026237e-

In [ ]:
M = tf.random.uniform(shape=[1,224,224,3])
print(M)
squeezed_M = tf.squeeze(M)
print(squeezed_M)

tf.Tensor(
[[[[0.88617194 0.31975305 0.96037436]
   [0.9235139  0.9998435  0.5416657 ]
   [0.99395466 0.6875576  0.1814214 ]
   ...
   [0.5551114  0.37019336 0.69272685]
   [0.6522975  0.56978905 0.5724205 ]
   [0.868374   0.64062893 0.22550702]]

  [[0.07482469 0.7029654  0.88437426]
   [0.28549337 0.8742231  0.25903034]
   [0.25968897 0.11492515 0.22962582]
   ...
   [0.6634495  0.19336104 0.81642973]
   [0.5729947  0.94642603 0.60866165]
   [0.7851982  0.82932746 0.4231168 ]]

  [[0.27995002 0.04292738 0.650228  ]
   [0.7743039  0.5163456  0.88162434]
   [0.8823972  0.30747986 0.4866011 ]
   ...
   [0.1458236  0.88210094 0.8290951 ]
   [0.8548591  0.2090745  0.19631529]
   [0.276101   0.8465487  0.36947477]]

  ...

  [[0.29420888 0.79768884 0.94076633]
   [0.5825466  0.5657337  0.11359715]
   [0.23495877 0.2316004  0.70308506]
   ...
   [0.8051413  0.7771344  0.32351434]
   [0.39424443 0.16906095 0.77581084]
   [0.70213103 0.3947482  0.95960176]]

  [[0.82172525 0.22536528 0.63868 

In [ ]:
N = tf.constant([0,1,2,3,4,5,6,7,8,9])
tf.argmax(N), tf.one_hot(N, depth = 10)

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>)